#!/usr/bin/env python3
"""Measure the ingested corpus and write docs/data-quality.md.

Regenerable: ``make quality``. Every number in the report comes from this script rather than
from prose, so the report cannot drift from the data.

The measurement this exists for is redaction density. CFPB narratives are scrubbed before
publication, and the Reg E and Reg Z obligations the agent has to check are made of exactly the
things a scrubber removes -- transaction dates, dollar amounts, notification dates. If those are
gone, `resolve()` can rarely satisfy `no_applicable_obligation` and the agent's dominant move
becomes `request_information`. That would be a premise-level finding, not a data-cleaning note.
"""

from __future__ import annotations

import argparse
import collections
import re
import statistics
import sys
from collections.abc import Iterable, Sequence
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import duckdb

from triage.scope import (
    IN_SCOPE_PRODUCT_LABELS,
    SPLIT_BOUNDS,
    CanonicalProduct,
    Label,
    Split,
    unrecognised_sub_product,
)

ROOT = Path(__file__).resolve().parent.parent

#: The CFPB replaces redacted spans with runs of X. Two or more, because "XX" appears in
#: ordinary text far less often than a single X does.
REDACTION = re.compile(r"X{2,}")

#: A dollar amount that survived scrubbing, e.g. "$35.00". Reg E liability tiers and Reg Z
#: dispute thresholds are dollar-denominated, so this is the input those obligations need.
SURVIVING_AMOUNT = re.compile(r"\$\s?\d[\d,]*(?:\.\d{2})?\b")

#: A redacted amount, e.g. "{$XX.00}" or "$XXXX".
REDACTED_AMOUNT = re.compile(r"\{?\$\s?X{2,}")

#: A date that survived scrubbing. Reg E's 10-business-day window and Reg Z's 60-day assertion
#: window are both measured from a date in the narrative.
SURVIVING_DATE = re.compile(
    r"\b(?:\d{1,2}[/-]\d{1,2}[/-]\d{2,4}"
    r"|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{1,2})\b"
)
REDACTED_DATE = re.compile(r"\bXX/XX/(?:XXXX|\d{4})\b")


def one(con: duckdb.DuckDBPyConnection, sql: str, params: Sequence[object] = ()) -> Any:
    """Run a query expected to return exactly one row and give back its first column.

    DuckDB's `fetchone` is typed as optional. Unwrapping it here once, loudly, beats an
    `assert` or a `# type: ignore` at each of the two dozen call sites below.
    """
    row = con.execute(sql, list(params)).fetchone()
    if row is None:
        raise RuntimeError(f"query returned no rows: {sql}")
    return row[0]


def one_int(con: duckdb.DuckDBPyConnection, sql: str, params: Sequence[object] = ()) -> int:
    value = one(con, sql, params)
    return int(value) if value is not None else 0


def pct(numerator: int, denominator: int) -> str:
    return f"{numerator / denominator:.2%}" if denominator else "n/a"


def table(header: Sequence[str], rows: Iterable[Sequence[object]]) -> list[str]:
    aligns = ["---" if i == 0 else "---:" for i in range(len(header))]
    out = ["| " + " | ".join(header) + " |", "|" + "|".join(aligns) + "|"]
    out += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--parquet", type=Path, default=ROOT / "data" / "complaints.parquet")
    parser.add_argument("--out", type=Path, default=ROOT / "docs" / "data-quality.md")
    args = parser.parse_args(argv)

    if not args.parquet.exists():
        print(f"{args.parquet} does not exist. Run `make fetch` first.", file=sys.stderr)
        return 1

    con = duckdb.connect()
    # DuckDB will not accept a prepared parameter in DDL, so the path is inlined. It comes from
    # argparse rather than from data, and the quote doubling keeps a path with an apostrophe in
    # it from ending the string early.
    literal = str(args.parquet).replace("'", "''")
    con.execute(f"CREATE VIEW c AS SELECT * FROM read_parquet('{literal}')")
    total: int = one_int(con, "SELECT count(*) FROM c")

    lines: list[str] = [
        "# Data quality",
        "",
        "Generated by `scripts/quality_report.py` from `data/complaints.parquet`. "
        "Regenerate with `make quality`.",
        "",
        f"Measured {datetime.now(UTC).date().isoformat()} over **{total:,}** in-scope narrative "
        f"complaints, {SPLIT_BOUNDS[0][1]} to {SPLIT_BOUNDS[-1][2]}, across "
        f"{len(IN_SCOPE_PRODUCT_LABELS)} raw product labels.",
        "",
        "---",
        "",
    ]

    # -- 1. Redaction -------------------------------------------------------------------
    narratives: list[str] = [
        row[0] for row in con.execute("SELECT narrative FROM c").fetchall()
    ]
    with_redaction = sum(1 for n in narratives if REDACTION.search(n))
    spans = [len(REDACTION.findall(n)) for n in narratives]
    lengths = [len(n) for n in narratives]
    amt_surv = sum(1 for n in narratives if SURVIVING_AMOUNT.search(n))
    amt_red = sum(1 for n in narratives if REDACTED_AMOUNT.search(n))
    date_surv = sum(1 for n in narratives if SURVIVING_DATE.search(n))
    date_red = sum(1 for n in narratives if REDACTED_DATE.search(n))

    lines += [
        "## 1. Redaction, and what survives it",
        "",
        "The CFPB scrubs narratives before publication, replacing redacted spans with runs of",
        "`X`. This matters more than a typical data-quality note, because the obligations the",
        "agent must check are made of exactly what a scrubber removes: Reg E's 10-business-day",
        "investigation window, Reg Z's 60-day assertion window, and the $50 / $500 liability",
        "tiers are all keyed to a date or an amount in the complaint.",
        "",
        *table(
            ["Property", "Complaints", "Share"],
            [
                ["Narrative contains at least one redacted span", f"{with_redaction:,}",
                 pct(with_redaction, total)],
                ["Contains a **surviving** dollar amount (`$35.00`)", f"{amt_surv:,}",
                 pct(amt_surv, total)],
                ["Contains a **redacted** dollar amount (`{$XX.00}`)", f"{amt_red:,}",
                 pct(amt_red, total)],
                ["Contains a **surviving** date (`3/14/2025`)", f"{date_surv:,}",
                 pct(date_surv, total)],
                ["Contains a **redacted** date (`XX/XX/XXXX`)", f"{date_red:,}",
                 pct(date_red, total)],
            ],
        ),
        "",
        f"Redacted spans per narrative: median {statistics.median(spans):.0f}, "
        f"mean {statistics.fmean(spans):.1f}, max {max(spans):,}.",
        "",
        f"Narrative length in characters: median {statistics.median(lengths):,.0f}, "
        f"mean {statistics.fmean(lengths):,.0f}, "
        f"p10 {sorted(lengths)[total // 10]:,}, p90 {sorted(lengths)[total * 9 // 10]:,}, "
        f"max {max(lengths):,}.",
        "",
    ]

    # -- 2. Duplicate and template narratives -------------------------------------------
    dup_rows = one_int(con, 
        "SELECT count(*) AS n FROM (SELECT narrative FROM c GROUP BY narrative HAVING "
        "count(*) > 1)"
    )
    dup_complaints: int = one_int(con, "SELECT coalesce(sum(n), 0) FROM "
        "(SELECT count(*) AS n FROM c GROUP BY narrative HAVING count(*) > 1)")
    top_dupes = con.execute(
        "SELECT count(*) AS n, any_value(split) AS split, substr(narrative, 1, 90) AS head "
        "FROM c GROUP BY narrative HAVING count(*) > 1 ORDER BY n DESC LIMIT 5"
    ).fetchall()

    lines += [
        "## 2. Exactly duplicated narratives",
        "",
        "Bulk submissions produce identical text at volume. This is the reason `similar_to` "
        "needs a same-event guard: a retrieval that returns fifty copies of one template is "
        "not evidence, and it would let one submission campaign dominate the agent's context.",
        "",
        f"- Distinct narratives appearing more than once: **{dup_rows:,}**",
        f"- Complaints sharing a narrative with at least one other: **{dup_complaints:,}** "
        f"({pct(dup_complaints, total)})",
        "",
        *table(
            ["Copies", "Split", "First 90 characters"],
            [[f"{n:,}", s, f"`{h.strip()[:90]}`"] for n, s, h in top_dupes],
        ),
        "",
    ]

    # -- 3. Nulls -----------------------------------------------------------------------
    nullable = ["sub_product", "sub_issue", "state", "tags", "company_public_response"]
    null_rows = []
    for column in nullable:
        # `column` comes from the fixed list above, never from input.
        missing = one_int(con, f"SELECT count(*) FROM c WHERE {column} IS NULL")
        null_rows.append([f"`{column}`", f"{missing:,}", pct(missing, total)])

    lines += [
        "## 3. Missing values",
        "",
        "Every other field is populated on every row. `complaint_id`, `date_received`, "
        "`date_sent_to_company`, `product`, `issue`, `narrative`, `company`, `zip_code`, "
        "`timely`, `company_response` and `submitted_via` have no nulls in the corpus, which "
        "is asserted at parse time rather than assumed -- a missing one raises.",
        "",
        *table(["Field", "Null", "Share"], null_rows),
        "",
    ]

    # -- 4. ZIP codes -------------------------------------------------------------------
    zip_rows = con.execute(
        "SELECT CASE "
        "  WHEN regexp_matches(zip_code, '^[0-9]{5}$') THEN 'full 5-digit' "
        "  WHEN regexp_matches(zip_code, '^[0-9]{3}XX$') THEN 'truncated (123XX)' "
        "  WHEN regexp_matches(zip_code, '^[0-9]+$') THEN 'numeric, not 5 digits' "
        "  ELSE 'other' END AS shape, count(*) AS n "
        "FROM c GROUP BY shape ORDER BY n DESC"
    ).fetchall()

    lines += [
        "## 4. ZIP code shape",
        "",
        "DESIGN.md described this field as a partial ZIP. It is not uniformly partial, which "
        "is worth stating plainly: some rows carry a full five-digit code.",
        "",
        *table(["Shape", "Complaints", "Share"],
               [[s, f"{n:,}", pct(n, total)] for s, n in zip_rows]),
        "",
        "Nothing in the model reads geography, so this is recorded rather than acted on. It is "
        "in the report because a public repository should say what identifying detail its data "
        "carries, not because the agent uses it.",
        "",
    ]

    # -- 5. Splits and labels -----------------------------------------------------------
    split_rows = []
    for split in Split:
        n: int = one_int(con, "SELECT count(*) FROM c WHERE split = ?", [split.value])
        if n == 0:
            continue
        pos = one_int(
            con,
            "SELECT count(*) FROM c WHERE split = ? AND label = ?",
            [split.value, Label.NEEDED_HUMAN.value],
        )
        excl = one_int(
            con,
            "SELECT count(*) FROM c WHERE split = ? AND label = ?",
            [split.value, Label.EXCLUDED.value],
        )
        split_rows.append([split.value, f"{n:,}", pct(pos, n), f"{excl:,}"])

    product_rows = []
    for product in CanonicalProduct:
        n = one_int(con, "SELECT count(*) FROM c WHERE canonical_product = ?", [product.value])
        pos = one_int(
            con,
            "SELECT count(*) FROM c WHERE canonical_product = ? AND label = ?",
            [product.value, Label.NEEDED_HUMAN.value],
        )
        product_rows.append([product.value, f"{n:,}", pct(pos, n)])

    label_rows = con.execute(
        "SELECT company_response, count(*) AS n FROM c GROUP BY 1 ORDER BY n DESC"
    ).fetchall()

    lines += [
        "## 5. Splits, products, and the label",
        "",
        *table(["Split", "Complaints", "Positive class", "Excluded outcome"], split_rows),
        "",
        "`Positive class` is the share whose recorded `company_response` granted relief of any "
        "kind. `Excluded outcome` counts `Untimely response` and `In progress`, which are "
        "dropped from the eval rather than mapped to a class.",
        "",
        *table(["Canonical product", "Complaints", "Positive class"], product_rows),
        "",
        *table(["`company_response`", "Complaints", "Share"],
               [[f"`{r}`", f"{n:,}", pct(n, total)] for r, n in label_rows]),
        "",
    ]

    # -- 6. Taxonomy --------------------------------------------------------------------
    pairs = con.execute(
        "SELECT product_label, sub_product, count(*) AS n FROM c GROUP BY 1, 2 ORDER BY n DESC"
    ).fetchall()
    unrecognised = [(p, s, n) for p, s, n in pairs if unrecognised_sub_product(p, s)]
    issue_tuples: int = one_int(
        con,
        "SELECT count(*) FROM "
        "(SELECT DISTINCT canonical_product, sub_product, issue, sub_issue FROM c)",
    )
    distinct_issues: int = one_int(con, "SELECT count(DISTINCT issue) FROM c")
    shared_issues = con.execute(
        "SELECT issue, count(DISTINCT canonical_product) AS p FROM c GROUP BY 1 HAVING p > 1 "
        "ORDER BY p DESC, issue LIMIT 8"
    ).fetchall()
    retired: int = one_int(con, 
        "SELECT count(*) FROM c WHERE product_label = 'Credit card or prepaid card'"
    )
    retired_split = con.execute(
        "SELECT canonical_product, count(*) AS n FROM c "
        "WHERE product_label = 'Credit card or prepaid card' GROUP BY 1 ORDER BY n DESC"
    ).fetchall()

    lines += [
        "## 6. Taxonomy",
        "",
        f"- Distinct `issue` values: **{distinct_issues}**",
        f"- Distinct `(canonical_product, sub_product, issue, sub_issue)` tuples: "
        f"**{issue_tuples:,}** -- this is what `IssueCategory` is keyed on",
        f"- `(product, sub_product)` pairs observed: **{len(pairs)}**, of which "
        f"**{len(unrecognised)}** are outside the vocabulary declared in `scope.py`",
        "",
        f"The retired `Credit card or prepaid card` label carries **{retired:,}** complaints "
        f"({pct(retired, total)}), split back into canonical products by `sub_product`:",
        "",
        *table(["Canonical product", "Complaints", "Share of the retired label"],
               [[p, f"{n:,}", pct(n, retired)] for p, n in retired_split]),
        "",
        "`issue` values that occur under more than one canonical product -- the reason "
        "`IssueCategory` cannot be keyed on `issue` alone:",
        "",
        *table(["`issue`", "Canonical products"],
               [[f"`{i}`", p] for i, p in shared_issues]),
        "",
    ]

    if unrecognised:
        lines += [
            "Sub-products outside the declared vocabulary. These resolve via their product "
            "label, which is unambiguous for all of them, but they are listed so the "
            "vocabulary in `scope.py` can be updated deliberately:",
            "",
            *table(["Product label", "Sub-product", "Complaints"],
                   [[p, s or "(none)", f"{n:,}"] for p, s, n in unrecognised[:20]]),
            "",
        ]

    # -- 7. Companies -------------------------------------------------------------------
    distinct_companies: int = one_int(con, "SELECT count(DISTINCT company) FROM c")
    top_companies = con.execute(
        "SELECT company, count(*) AS n, "
        "  count(*) FILTER (WHERE label = 'needed_human') AS pos "
        "FROM c GROUP BY 1 ORDER BY n DESC LIMIT 10"
    ).fetchall()
    singletons: int = one_int(con, 
        "SELECT count(*) FROM (SELECT company FROM c GROUP BY 1 HAVING count(*) = 1)"
    )

    lines += [
        "## 7. Respondents",
        "",
        f"- Distinct `company` strings: **{distinct_companies:,}**",
        f"- Appearing exactly once: **{singletons:,}** ({pct(singletons, distinct_companies)} "
        f"of respondents)",
        "",
        "Relief rate varies several-fold across the largest respondents, which is why "
        "`Company.relief_rate` is computed per split from that split's past only, and why "
        "whether the agent should see the company name at all is still open "
        "(`docs/open-questions.md` C7).",
        "",
        *table(["Respondent", "Complaints", "Positive class"],
               [[c, f"{n:,}", pct(p, n)] for c, n, p in top_companies]),
        "",
    ]

    # -- 8. Date anomalies --------------------------------------------------------------
    backwards: int = one_int(con, 
        "SELECT count(*) FROM c WHERE date_sent_to_company < date_received"
    )
    same_day: int = one_int(con, 
        "SELECT count(*) FROM c WHERE date_sent_to_company = date_received"
    )
    median_lag = one(con, "SELECT median(datediff('day', date_received, date_sent_to_company)) "
                          "FROM c")
    max_lag = one_int(con, "SELECT max(datediff('day', date_received, date_sent_to_company)) "
                           "FROM c")

    lines += [
        "## 8. Dates",
        "",
        f"- Sent to the company before it was received: **{backwards:,}** "
        f"({pct(backwards, total)})",
        f"- Sent the same day: **{same_day:,}** ({pct(same_day, total)})",
        f"- Median days from receipt to referral: **{median_lag:.0f}**, "
        f"maximum **{max_lag:,}**",
        "",
        "`date_sent_to_company` is withheld from the agent regardless: it postdates the moment "
        "a triage decision would have been made.",
        "",
        "---",
        "",
        "## What this changes",
        "",
        "Written after the numbers above, not before them. See `DECISIONS.md`.",
        "",
    ]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({len(lines)} lines) over {total:,} complaints")

    counted = collections.Counter(
        {"redacted": with_redaction, "surviving_amount": amt_surv, "surviving_date": date_surv}
    )
    print("  headline:", dict(counted))
    return 0


if __name__ == "__main__":
    sys.exit(main())
